services:
  _defaults:
    autowire: false
    autoconfigure: false

  App\ShoppingCart\Cart\Infrastructure\Persistence\Dbal\DbalCartRepository:
    arguments:
      - '@Doctrine\DBAL\Connection'

  App\ShoppingCart\Product\Infrastructure\Persistence\Dbal\DbalProductRepository:
    arguments:
      - '@Doctrine\DBAL\Connection'

  App\ShoppingCart\Cart\Domain\Cart\CartRepository: '@App\ShoppingCart\Cart\Infrastructure\Persistence\Dbal\DbalCartRepository'
  App\ShoppingCart\Cart\Domain\Product\ProductRepository: '@App\ShoppingCart\Product\Infrastructure\Persistence\Dbal\DbalProductRepository'


  App\ShoppingCart\Cart\Application\Cart\CartCreator:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Cart\CartConfirmed:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Item\ItemCreator:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'
      - '@App\ShoppingCart\Cart\Domain\Product\ProductRepository'

  App\ShoppingCart\Cart\Application\Item\ItemsEliminator:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Item\ItemEliminator:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Cart\CartFinder:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Item\ItemIncrementor:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Application\Item\ItemDecrement:
    arguments:
      - '@App\ShoppingCart\Cart\Domain\Cart\CartRepository'

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\AddCart\AddCartController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Cart\CartCreator'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\ConfirmedCart\ConfirmedCartController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Cart\CartConfirmed'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\AddItem\AddItemController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Item\ItemCreator'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\RemoveItem\RemoveItemController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Item\ItemEliminator'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\RemoveAllItems\RemoveAllItemController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Item\ItemsEliminator'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\TotalAmount\TotalAmountController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Cart\CartFinder'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\IncreaseItem\IncreaseItemController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Item\ItemIncrementor'
    tags:
      - controller.service_arguments

  App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\DecreaseItem\DecreaseItemController:
    arguments:
      - '@App\ShoppingCart\Cart\Application\Item\ItemDecrement'
    tags:
      - controller.service_arguments