services:
  _defaults:
    autowire: false
    autoconfigure: false

  App\ShoppingCart\Product\Infrastructure\Persistence\Dbal\DbalProductRepository:
    arguments:
      - '@Doctrine\DBAL\Connection'

  App\ShoppingCart\Product\Domain\ProductRepository: '@App\ShoppingCart\Product\Infrastructure\Persistence\Dbal\DbalProductRepository'

  App\ShoppingCart\Product\Application\ProductCreator:
    arguments:
      - '@App\ShoppingCart\Product\Domain\ProductRepository'

  App\ShoppingCart\Product\Infrastructure\Ui\Http\Controller\AddProduct\AddProductController:
    arguments:
      - '@App\ShoppingCart\Product\Application\ProductCreator'
    tags:
      - controller.service_arguments