add_seller:
  path: /seller/add
  controller: App\ShoppingCart\Seller\Infrastructure\Ui\Http\Controller\AddSeller\AddSellerController

remove_seller:
  path: /seller/remove
  controller: App\ShoppingCart\Seller\Infrastructure\Ui\Http\Controller\RemoveSeller\RemoveSellerController

add_product:
  path: /product/add
  controller: App\ShoppingCart\Product\Infrastructure\Ui\Http\Controller\AddProduct\AddProductController

remove_product:
  path: /product/remove
  controller: App\ShoppingCart\Product\Infrastructure\Ui\Http\Controller\RemoveProduct\RemoveProductController

add_cart:
  path: /cart/add
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\AddCart\AddCartController

confirmed_cart:
  path: /cart/confirmed
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\ConfirmedCart\ConfirmedCartController

add_item:
  path: cart/item/add
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\AddItem\AddItemController

remove_item:
  path: cart/item/remove
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\RemoveItem\RemoveItemController

total_amount_cart:
  path: cart/total_amount
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\TotalAmount\TotalAmountController

increase_item_cart:
  path: cart/item/increment
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\IncreaseItem\IncreaseItemController

decrease_item_cart:
  path: cart/item/decrease
  controller: App\ShoppingCart\Cart\Infrastructure\Ui\Http\Controller\Cart\DecreaseItem\DecreaseItemController