add_seller:
  path: /seller/add
  controller: App\ShoppingCart\Seller\Infrastructure\Ui\Http\Controller\AddSeller\AddSellerController

remove_seller:
  path: /seller/remove
  controller: App\ShoppingCart\Seller\Infrastructure\Ui\Http\Controller\RemoveSeller\RemoveSellerController

add_product:
  path: /product/add
  controller: App\ShoppingCart\Product\Infrastructure\Ui\Http\Controller\AddProduct\AddProductController