services:
  _defaults:
    autowire: false
    autoconfigure: false

  App\ShoppingCart\Seller\Infrastructure\Persistence\Dbal\DbalSellerRepository:
    arguments:
      - '@Doctrine\DBAL\Connection'

  App\ShoppingCart\Seller\Domain\SellerRepository: '@App\ShoppingCart\Seller\Infrastructure\Persistence\Dbal\DbalSellerRepository'

  App\ShoppingCart\Seller\Application\SellerCreator:
    arguments:
      - '@App\ShoppingCart\Seller\Domain\SellerRepository'

  App\ShoppingCart\Seller\Infrastructure\Ui\Http\Controller\AddSeller\AddSellerController:
    arguments:
      - '@App\ShoppingCart\Seller\Application\SellerCreator'
    tags:
      - controller.service_arguments